### ISSUE TITLE
Seperate delivery objects per device token

### ISSUE THREAD

**Issue by antonivanopoulos** [Papercloud/notify_user#46]
At the moment we're only generating one `Delivery` per channel per notification, i.e. if a notification uses APNS and GCM channels, it will create two `Delivery`s (despite the fact that the target user may not have devices for either channel).

Proposing here the idea that instead, in the case of these channels, we create individual delivery objects per device the user has registered (changed the wording here slightly as I started typing it, because it occurred to me that this change means some slightly janky behaviour in regards to email channel) for that channel.

**Comment by knightstick** [comment]
👍 +1

**Comment by knightstick** [comment]
@timjcook @RustComet does this fit with your usage at the moment?

**Comment by RustComet** [comment]
@knightstick At the moment we are storing multiple delivery responses on 1 delivery object. I think separating deliveries to be per device makes more sense.

**Comment by antonivanopoulos** [comment]
Implemented in #47
