### ISSUE TITLE
NotifyUser called within hooks

### ISSUE THREAD

**Issue by antonivanopoulos** [Papercloud/notify_user#6]
It's not mentioned in the docs that you need to use `after_commit :on => :create` hooks within the model that calls `.notify` to send new notifications, which leads to the issues I mentioned in #5. Had to read up on Sidekiq itself to figure it out.

Need to either make this obvious in the README for the project, or we could potentially move the logic within [#notify](https://github.com/Papercloud/notify_user/blob/master/app/models/notify_user/base_notification.rb#L102) into an after_commit commit hook, which lets NotifyUser worry about waiting for the transaction to be complete before trying to deliver a notification.

**Comment by dawilster** [comment]
@antonivanopoulos are you sure this was what was causing the issue? the notification object is saved immediately after you call .notify before any sidekiq jobs are scheduled.
